In [9]:
# Programme to multiply two Matrixes.
A = [[1,2,4],
     [5,6,7],
     [8,9,1]]
B= [[3,4,5],
   [1,3,2],
   [9,4,3]]

R = [[0,0,0],
    [0,0,0],
    [0,0,0]]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            R[i][j]+= A[i][k] * B[k][j]
for r in R:
    print(r)
    

[41, 26, 21]
[84, 66, 58]
[42, 63, 61]


In [29]:
# Programme to add two Matrixes.
A = [[1,2,4],
     [5,6,7],
     [8,9,1]]
B= [[3,4,5],
   [1,3,2],
   [9,4,3]]

R = [[0,0,0],
    [0,0,0],
    [0,0,0]]

for i in range(len(A)):
    for j in range(len(B[0])):
         R[i][j] = A[i][j] + B[i][j]
for r in R:
    print(r)

[4, 6, 9]
[6, 9, 9]
[17, 13, 4]


In [20]:
#Python Program to Transpose a Matrix
import numpy as np
matrix =np.array([[1,2,4],[5,6,7],[8,9,1]])
print(matrix.T)



[[1 5 8]
 [2 6 9]
 [4 7 1]]


In [25]:
#Python Program to Sort Words in Alphabetic Order

str =input("Enter a string in lower case letters : ")
s= str.split()
s.sort()
for w in s:
    print(w)



Enter a string in lower case letters : enter a string in lower case letters
a
case
enter
in
letters
lower
string


In [28]:
#Python Program to Remove Punctuation From a String

def_punctuation = "$^&*=+?!_-."
string = "Hi!... How r you."

without_punctuation = " "
for i in string:
    if i not in def_punctuation:
        without_punctuation =  without_punctuation + i
        
print( without_punctuation )

 

 Hi How r you
